name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number, without v prefix"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
